version: '3'

services:
  pokemon-api:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    container_name: pokemon-backend
    networks:
      - pokemon-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pokemon-frontend
    ports:
      - "80:80"
    depends_on:
      - pokemon-api
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge 