AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pokemon API SAM Template

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java11
    Architectures:
      - x86_64
    Environment:
      Variables:
        SPRING_CLOUD_FUNCTION_DEFINITION: listPokemon,getPokemon
  Api:
    Cors:
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  PokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.pokemon.handler.PokemonHandler
      Runtime: java11
      CodeUri: target/pokemon-api-1.0-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 30
      Events:
        GetPokemon:
          Type: Api
          Properties:
            Path: /pokemon/{name}
            Method: GET
        ListPokemon:
          Type: Api
          Properties:
            Path: /pokemon
            Method: GET
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: listPokemon,getPokemon

Outputs:
  PokemonApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  PokemonFunction:
    Description: Pokemon Lambda Function ARN
    Value: !GetAtt PokemonFunction.Arn 